server:
  port: 8080

spring:
  application:
    name: craft-backend
  datasource:
    url: jdbc:mysql://localhost:3306/craft?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  mvc:
    format:
      date-time: yyyy-MM-dd'T'HH:mm:ss

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    default-enum-type-handler: org.apache.ibatis.type.EnumTypeHandler

logging:
  level:
    root: info
    io.github.anthem37: debug